# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.4.1

    - name: Build
      run: |
        echo "${{ steps.conan.outputs.version }}"
        mkdir -p /home/runner/.conan2/profiles
        cp ci.conan.txt /home/runner/.conan2/profiles/default
        conan install conanfile.py --build=missing --output-folder=build -sbuild_type=Release
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
#        release_name: ${{ steps.version.outputs.version }}
        release_name: test-${{ github.ref }}
        tag_name: test-${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload GNU/Linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/kp_record
        asset_name: kp_record
        asset_content_type: application/binary
